# This programa show you a Heads or Tails bases on random number generated by "random" library
# The random number generated is between 0 and 1
import random

num = random.randint(0, 1)   # RNGesus will give us a random number between 0 and 1

if num > 0.5:
  print("Heads")
else:
  print("Tails")


#End